/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cfig_jgrep_AnsiColor */

#ifndef _Included_org_cfig_jgrep_AnsiColor
#define _Included_org_cfig_jgrep_AnsiColor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cfig_jgrep_AnsiColor
 * Method:    isStdinTty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cfig_jgrep_AnsiColor_isStdinTty
  (JNIEnv *, jobject);

/*
 * Class:     org_cfig_jgrep_AnsiColor
 * Method:    isStdoutTty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cfig_jgrep_AnsiColor_isStdoutTty
  (JNIEnv *, jobject);

/*
 * Class:     org_cfig_jgrep_AnsiColor
 * Method:    nativeTest
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cfig_jgrep_AnsiColor_nativeTest
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
